services:
  mongo: 
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports: 
      - 27017:27017

  backend:
    build: ./MESI-Backend
    restart: unless-stopped
    ports:
      - 4000:4000
    links:
      - mongo
  
  frontend:
    build: ./MESI-Frontend
    restart: unless-stopped
    ports:
      - 80:80
