name: CI - Unit Tests

on: 
  push:
  pull_request:
    branches:
      - develop

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci
        working-directory: ./MESI-Frontend

      - name: Run tests 
        run: npm run test:prod
        working-directory: ./MESI-Frontend