name: CI - E2E Tests

on: 
  pull_request:
    branches:
      - develop

jobs:
  build_front:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Start containers 
        run: docker-compose up -d

      - name: Install dependencies
        run: npm ci
        working-directory: ./MESI-Test

      - name: Run e2e tests
        run: npm test
        working-directory: ./MESI-Test